version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala:
  - 3.0.0-RC3

env:
  - ADOPTOPENJDK=8

install:
  - git fetch --tags # get all tags for sbt-dynver

script: ./build.sh

notifications:
  email:
    - seth.tisue@lightbend.com
    - andy@hicks.net
